server:
  port: 8081

spring:
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB

application:
  file:
    upload-dir: /mnt/dados/git/wedson.silva/lab-unoserver/upload
